[package]
name = "kartzrbx/module3d"
description = "A module with unique features and advanced methods for the effective use of three-dimensional models."
liscence = "MIT"
authors = ["KartzRbx"]
version = "1.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["aftman.toml"]

[dependencies]
knit = "sleitnick/knit@1.7.0"
